[versions]
agp = "8.7.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
lifecycle = "2.6.2" # 또는 사용 중인 버전에 맞춰 조절

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-process = "androidx.lifecycle:lifecycle-process:2.6.2"
lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime:2.6.2"
lifecycle-common-java8 = "androidx.lifecycle:lifecycle-common-java8:2.6.2"

[plugins]
android-application = { id = "com.android.application", version = "8.6.0" }

